-- Replace one-line project summaries with readable CMS-backed project dossiers.
UPDATE `projects` SET `body_md` = '## Overview\n\nUniversal Music Store is a worker-native commerce platform for product discovery, checkout, customer accounts, catalog operations, fulfillment, CMS, and staff workflows.\n\n## What I built\n\n- Storefront and product discovery flows\n- Admin and catalog operations\n- Checkout and customer account foundations\n- Fulfillment and internal workflow surfaces\n\n## Stack\n\nNext.js, edge workers, Medusa, and Supabase.' WHERE `slug` = 'universal-music-store';
--> statement-breakpoint
UPDATE `projects` SET `body_md` = '## Overview\n\nMeta-Architect is a quality and evidence system for AI coding agents. It makes agent work prove each stage before the next one opens.\n\n## What I built\n\n- Architecture and design gates\n- Evidence and logic verification\n- Security and experience review stages\n- Build verification and reusable agent plugins\n\n## Stack\n\nTypeScript, Codex workflows, and MCP.' WHERE `slug` = 'meta-architect';
--> statement-breakpoint
UPDATE `projects` SET `body_md` = '## Overview\n\nLending-Mind Protocol turns explicit engineering preferences into signed Mind Packages, bounded evaluations, and reviewable evidence for AI-assisted software development.\n\n## What I built\n\n- Local-first control-plane concepts\n- Signed preference and evaluation packages\n- Bounded execution and review evidence\n- A protocol for durable engineering judgment\n\n## Stack\n\nRust and Node.js.' WHERE `slug` = 'lending-mind-protocol';
--> statement-breakpoint
UPDATE `projects` SET `body_md` = '## Overview\n\nKwago is a private local-first calendar with on-device AI drafting, conflict review, and encrypted sync.\n\n## What I built\n\n- Intent parsing for calendar actions\n- Conflict detection and review\n- On-device intelligence for private schedules\n- Local persistence and encrypted synchronization\n\n## Stack\n\nReact Native, ExecuTorch, and SQLite.' WHERE `slug` = 'kwago';
--> statement-breakpoint
UPDATE `projects` SET `body_md` = '## Overview\n\nAmbiOS AI is an operational workspace for human judgment and governed agent action.\n\n## What I built\n\n- Operational context and incident response\n- Guardrails, approvals, budgets, and integrations\n- Documentation proposals and governed actions\n- WebMCP tools behind shared server-side policy\n\n## Stack\n\nNext.js and WebMCP.' WHERE `slug` = 'ambios-ai';
--> statement-breakpoint
UPDATE `projects` SET `body_md` = '## Overview\n\nRoblox AI OS is a Roblox Studio operating layer for disciplined Codex-powered creator workflows.\n\n## What I built\n\n- Briefing and planning workflows\n- Roblox-native build and review guidance\n- Verification loops for creator output\n- Psychology-aware design prompts and tools\n\n## Stack\n\nCodex, Roblox Studio, and TypeScript.' WHERE `slug` = 'roblox-ai-os';
--> statement-breakpoint
UPDATE `projects` SET `body_md` = '## Overview\n\nGo-Mirofish is a local-first swarm-intelligence workflow for prediction and simulation. It uploads documents, builds a graph, runs simulations, and produces prediction reports.\n\n## What I built\n\n- Document ingestion and graph construction\n- Simulation and prediction workflows\n- A Go gateway with a Vue interface\n- A local product path without a Python process on the hot path\n\n## Stack\n\nGo, Vue.js, and Vite.' WHERE `slug` = 'go-mirofish';
--> statement-breakpoint
UPDATE `projects` SET `body_md` = '## Overview\n\nPremortem is a reviewer-first predictive audit system for repositories.\n\n## What I built\n\n- Bounded repository context ingestion\n- Fixed specialist review passes\n- Traceable issue candidates\n- Human approval before publication to GitLab\n\n## Stack\n\nNext.js, Prisma, and GitLab.' WHERE `slug` = 'premortem';
--> statement-breakpoint
UPDATE `projects` SET `body_md` = '## Overview\n\nllmfaucet provides one OpenAI-compatible endpoint for available free AI capacity without buying credits or funding paid balances.\n\n## What I built\n\n- Provider capacity aggregation\n- Smart routing and fallback\n- Streaming responses and model selectors\n- Transparent limits and availability behavior\n\n## Stack\n\nOpenAI-compatible APIs and edge infrastructure.' WHERE `slug` = 'llmfaucet';
--> statement-breakpoint
UPDATE `projects` SET `body_md` = '## Overview\n\nHyperAgent is an AI-assisted smart-contract development system inside HyperKit Labs.\n\n## What I built\n\n- Natural-language specifications to contract artifacts\n- Automated audit and simulation stages\n- Deployment preparation and workflow orchestration\n- A path toward verified multi-chain development\n\n## Stack\n\nPython, Solidity, TypeScript, React, Node.js, and Supabase.' WHERE `slug` = 'hyperagent';
