export type ExperienceProgressIcon = {
  name: string;
  key: string;
};

export type ExperienceProgressEntry = {
  id: string;
  parentId?: string | null;
  year: string;
  company: string;
  status: string;
  role: string;
  description: string;
  logoKey?: string | null;
  logoUrl: string | null;
  project: string;
  projectDescription: string;
  icons: ExperienceProgressIcon[];
};

export type ExperienceProgressMeta = {
  entries: ExperienceProgressEntry[];
};

export const EXPERIENCE_TECH_OPTIONS = [
  { key: "n8n", name: "n8n" },
  { key: "framer", name: "Framer" },
  { key: "figma", name: "Figma" },
  { key: "rust", name: "Rust" },
  { key: "move", name: "Move" },
  { key: "visual-basic", name: "Visual Basic" },
  { key: "c", name: "C" },
  { key: "java", name: "Java" },
  { key: "mysql", name: "MySQL" },
  { key: "unreal", name: "Unreal Engine" },
  { key: "html5", name: "HTML5" },
  { key: "tailwind", name: "Tailwind CSS" },
  { key: "solidity", name: "Solidity" },
  { key: "python", name: "Python" },
  { key: "typescript", name: "TypeScript" },
  { key: "react", name: "React" },
  { key: "node", name: "Node.js" },
  { key: "supabase", name: "Supabase" },
  { key: "go", name: "Go" },
  { key: "vue", name: "Vue.js" },
  { key: "vite", name: "Vite" },
  { key: "javascript", name: "JavaScript" },
  { key: "mongo", name: "MongoDB" },
] as const;

export const fallbackExperienceProgress: ExperienceProgressEntry[] = [
  {
    id: "hyperkit",
    year: "2026",
    company: "HyperKit Labs",
    status: "CURRENT",
    role: "Co-Founder / Product Engineer",
    description:
      "Joined a three-person team to build developer infrastructure for smart contracts, then continued shaping AI-assisted generation, auditing, and practical product workflows.",
    logoUrl: "/assets/associates/hyperkit.svg",
    logoKey: "brand.hyperkit",
    project: "HyperKit",
    projectDescription: "Developer infrastructure and AI-native tooling shaped through hackathon building, team leadership, and continued independent development.",
    icons: [
      { name: "TypeScript", key: "typescript" },
      { name: "Node.js", key: "node" },
      { name: "npmjs", key: "npm" },
    ],
  },
  {
    id: "hyperagent",
    parentId: "hyperkit",
    year: "2025",
    company: "HyperKit Labs",
    status: "SHIPPED",
    role: "Product Engineer",
    description:
      "Shipped an AI-powered smart contract platform from natural language to production-ready, audited contracts, and turned the work into public proof through hackathon wins.",
    logoUrl: "/v2/showcase/HyperAgent.png",
    logoKey: "project.hyperagent",
    project: "HyperAgent",
    projectDescription: "AI-powered smart contract generation, auditing, and deployment workflows.",
    icons: [
      { name: "Solidity", key: "solidity" },
      { name: "Python", key: "python" },
      { name: "TypeScript", key: "typescript" },
      { name: "React", key: "react" },
      { name: "Node.js", key: "node" },
      { name: "Supabase", key: "supabase" },
    ],
  },
  {
    id: "learning-path",
    year: "2025–26",
    company: "Technical Learning Path",
    status: "LEARNING PATH",
    role: "Software foundations → AI and Web3",
    description:
      "June 2024 — C programming language fundamentals, memory management, and system programming. January 2025 — MySQL database fundamentals, SQL queries, and data management. February–March 2025 — Unreal Engine Blueprint visual scripting, HTML5 fundamentals, semantic markup, responsive design, Tailwind CSS utility classes, custom components, and responsive layouts. April 2025 — Java OOP concepts, data structures, basic algorithms, and Visual Basic .NET Windows Forms with database connectivity. May–June 2025 — Solidity smart contracts, DeFi protocols, Web3 integration, Python scripting, automation, and data manipulation. July–August 2025 — TypeScript, JavaScript, React, Node.js, Express.js, RESTful APIs, MongoDB, and Supabase backend services. Current — n8n workflow automation, LLM integration, and AI-powered processes.",
    logoUrl: null,
    project: "Roadmap learning path",
    projectDescription: "A dated progression from programming and database fundamentals into full-stack, AI automation, and Web3 systems.",
    icons: [
      { name: "C", key: "c" },
      { name: "MySQL", key: "mysql" },
      { name: "Unreal Engine", key: "unreal" },
      { name: "HTML5", key: "html5" },
      { name: "Tailwind CSS", key: "tailwind" },
      { name: "Java", key: "java" },
      { name: "Visual Basic", key: "visual-basic" },
      { name: "Solidity", key: "solidity" },
      { name: "Python", key: "python" },
      { name: "TypeScript", key: "typescript" },
      { name: "JavaScript", key: "javascript" },
      { name: "React", key: "react" },
      { name: "Node.js", key: "node" },
      { name: "MongoDB", key: "mongo" },
      { name: "Supabase", key: "supabase" },
      { name: "n8n", key: "n8n" },
    ],
  },
  {
    id: "fullstack",
    year: "2026",
    company: "Product Engineering",
    status: "PIVOT",
    role: "Software Developer",
    description:
      "Building Go-Mirofish, a local-first swarm intelligence engine that turns documents into simulations and prediction reports.",
    logoUrl: null,
    project: "Go-Mirofish",
    projectDescription: "A Go-native swarm intelligence engine with a Vue interface for local prediction workflows.",
    icons: [
      { name: "Go", key: "go" },
      { name: "Vue.js", key: "vue" },
      { name: "Vite", key: "vite" },
    ],
  },
  {
    id: "universal-music-store",
    parentId: "fullstack",
    year: "2026",
    company: "Independent practice",
    status: "PROJECT",
    role: "Platform Engineer",
    description: "Worker-native music commerce platform with storefront, admin operations, commerce workflows, and Supabase-backed services.",
    logoUrl: null,
    logoKey: "project.universal-music-store",
    project: "Universal Music Store",
    projectDescription: "Product discovery, checkout, customer accounts, catalog operations, fulfillment, and staff workflows.",
    icons: [
      { name: "Next.js", key: "nextjs" },
      { name: "Cloudflare Workers", key: "cloudflare-workers" },
      { name: "Medusa", key: "medusa" },
      { name: "Supabase", key: "supabase" },
    ],
  },
  {
    id: "meta-architect",
    parentId: "fullstack",
    year: "2026",
    company: "Independent practice",
    status: "PROJECT",
    role: "AI Systems Engineer",
    description: "Quality gates and evidence verification for AI coding agents, making each stage of agent work reviewable before the next one opens.",
    logoUrl: null,
    logoKey: "project.meta-architect",
    project: "Meta-Architect",
    projectDescription: "Design, evidence, logic, security, experience, and build verification for agent workflows.",
    icons: [
      { name: "TypeScript", key: "typescript" },
      { name: "Codex", key: "codex" },
      { name: "MCP", key: "mcp" },
    ],
  },
  {
    id: "lending-mind-protocol",
    parentId: "fullstack",
    year: "2026",
    company: "Independent practice",
    status: "PROJECT",
    role: "Systems Engineer",
    description: "A local-first control plane that makes engineering judgment executable through signed packages, bounded evaluations, and reviewable evidence.",
    logoUrl: null,
    logoKey: "project.lending-mind-protocol",
    project: "Lending-Mind Protocol",
    projectDescription: "Explicit engineering preferences turned into bounded, auditable AI-assisted software decisions.",
    icons: [
      { name: "Rust", key: "rust" },
      { name: "Node.js", key: "node" },
    ],
  },
  {
    id: "kwago",
    parentId: "fullstack",
    year: "2026",
    company: "Independent practice",
    status: "PROJECT",
    role: "Mobile / AI Engineer",
    description: "A private local-first calendar with on-device AI drafting, conflict review, and encrypted sync.",
    logoUrl: null,
    logoKey: "project.kwago",
    project: "Kwago",
    projectDescription: "On-device schedule intelligence that parses intent, detects conflicts, and protects calendar data.",
    icons: [
      { name: "React Native", key: "react-native" },
      { name: "ExecuTorch", key: "executorch" },
      { name: "SQLite", key: "sqlite" },
    ],
  },
  {
    id: "ambios-ai",
    parentId: "fullstack",
    year: "2026",
    company: "Independent practice",
    status: "PROJECT",
    role: "AI Systems Engineer",
    description: "An operational workspace for human judgment and governed agent action, with shared server-side controls.",
    logoUrl: null,
    logoKey: "project.ambios-ai",
    project: "AmbiOS AI",
    projectDescription: "Operational context, incident response, approvals, guardrails, budgets, integrations, and WebMCP tools.",
    icons: [
      { name: "Next.js", key: "nextjs" },
      { name: "WebMCP", key: "webmcp" },
    ],
  },
  {
    id: "roblox-ai-os",
    parentId: "fullstack",
    year: "2026",
    company: "Independent practice",
    status: "PROJECT",
    role: "Creator Tools Engineer",
    description: "A Roblox Studio operating layer for disciplined Codex-powered creator workflows.",
    logoUrl: null,
    logoKey: "project.roblox-ai-os",
    project: "Roblox AI OS",
    projectDescription: "Briefing, planning, building, review, verification, and psychology-aware design workflows for creators.",
    icons: [
      { name: "Codex", key: "codex" },
      { name: "Roblox Studio", key: "roblox-studio" },
      { name: "TypeScript", key: "typescript" },
    ],
  },
  {
    id: "premortem",
    parentId: "fullstack",
    year: "2026",
    company: "Independent practice",
    status: "PROJECT",
    role: "Developer Tools Engineer",
    description: "A reviewer-first predictive audit system for repositories with bounded context, specialist analysis, and human approval.",
    logoUrl: null,
    logoKey: "project.premortem",
    project: "Premortem",
    projectDescription: "Traceable issue candidates and reviewable repository audits before changes are published.",
    icons: [
      { name: "Next.js", key: "nextjs" },
      { name: "Prisma", key: "prisma" },
      { name: "GitLab", key: "gitlab" },
    ],
  },
  {
    id: "llmfaucet",
    parentId: "fullstack",
    year: "2026",
    company: "Independent practice",
    status: "PROJECT",
    role: "AI Infrastructure Engineer",
    description: "One OpenAI-compatible endpoint for available free AI capacity, with routing, fallback, streaming, and transparent limits.",
    logoUrl: null,
    logoKey: "project.llmfaucet",
    project: "llmfaucet",
    projectDescription: "Aggregated provider capacity through one compatible API surface with smart model selection.",
    icons: [
      { name: "OpenAI-compatible API", key: "openai-compatible-api" },
      { name: "Cloudflare Workers", key: "cloudflare-workers" },
    ],
  },
  {
    id: "foundation",
    year: "2023",
    company: "Software Foundations",
    status: "FOUNDATION",
    role: "Software Developer",
    description:
      "Started with fundamentals, databases, and the discipline of learning by building things that had to work.",
    logoUrl: null,
    project: "First systems",
    projectDescription: "The first database connections, interfaces, and software experiments that shaped the practice.",
    icons: [
      { name: "C", key: "c" },
      { name: "MySQL", key: "mysql" },
      { name: "Java", key: "java" },
      { name: "Visual Basic", key: "visual-basic" },
    ],
  },
  {
    id: "founders-direction",
    year: "2026",
    company: "Founder School & Client Work",
    status: "DIRECTION",
    role: "Founder / Product Engineer",
    description: "Studied purpose, validation, MVP building, and fundraising through Founders School, then led a Morph payment hackathon team while exploring freelance product work.",
    logoKey: "brand.founders-school",
    logoUrl: null,
    project: "Founders School → client work",
    projectDescription: "Turning technical execution into clearer product choices, stronger collaboration, and useful software for real clients.",
    icons: [],
  },
  {
    id: "hackathon-leadership",
    year: "2025",
    company: "Hackathon Leadership",
    status: "LEADERSHIP",
    role: "Hackathon Builder / Project Lead",
    description: "Moved from smart-contract and UI work into leading teams, defining roadmaps, documenting systems, shaping MVPs, and shipping under pressure.",
    logoUrl: null,
    project: "HyperHack → Hack2Build → Morph",
    projectDescription: "A sequence of team-building and leadership milestones: HyperHack placement, an Avalanche x402 win, and a Morph team led through delivery.",
    icons: [
      { name: "Solidity", key: "solidity" },
      { name: "React", key: "react" },
      { name: "TypeScript", key: "typescript" },
      { name: "EVM", key: "evm" },
    ],
  },
  {
    id: "builder-pivot",
    year: "2024",
    company: "Independent Builder",
    status: "PIVOT",
    role: "Student → Independent Builder",
    description: "Left a BSIT program when its curriculum no longer matched the problems being pursued, then chose to learn by shipping secure tools and studying smart-contract architecture.",
    logoUrl: null,
    project: "MetaWalletGen-CLI",
    projectDescription: "A secure Ethereum wallet-generation CLI with encrypted storage, flexible exports, and a focus on safer infrastructure.",
    icons: [
      { name: "Node.js", key: "node" },
      { name: "TypeScript", key: "typescript" },
      { name: "Solidity", key: "solidity" },
    ],
  },
  {
    id: "community-beginnings",
    year: "2022–24",
    company: "Project One Percent",
    status: "FOUNDATION",
    role: "Volunteer Discord Moderator → Community Builder",
    description: "Entered Web3 through volunteer community work, built relationships through events, and found the people and encouragement that opened the path toward Solidity and software development.",
    logoUrl: null,
    logoKey: "brand.discord",
    project: "Project One Percent",
    projectDescription: "The community starting point: moderation, presence-building, peer learning, and the relationships behind the later builder journey.",
    icons: [
      { name: "Community", key: "community" },
      { name: "Web3", key: "web3" },
    ],
  },
];
